### ISSUE TITLE
ModuleNotFoundError: No module named 'grapheneapi.grapheneclient

### ISSUE THREAD

**Issue by CBND01** [xeroc/python-graphenelib#135]
Traceback (most recent call last):
  File "Dbot5.py", line 12, in <module>
    from grapheneexchange import GrapheneExchange
  File "/usr/local/lib/python3.6/dist-packages/graphenelib-0.4.2-py3.6.egg/grapheneexchange/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/graphenelib-0.4.2-py3.6.egg/grapheneexchange/exchange.py", line 1, in <module>
ModuleNotFoundError: No module named 'grapheneapi.grapheneclient'

**Comment by xeroc** [comment]
Use a current version of graphenelib and update the code that calls it.
