### ISSUE TITLE
Graphenelib 0.6.3 is broken

### ISSUE THREAD

**Issue by bitfag** [xeroc/python-graphenelib#67]
Just try to initialize bitshares instance and you will get:

```python
% ./testcase.py 
Traceback (most recent call last):
  File "./testcase.py", line 7, in <module>
    bitshares = BitShares(node='wss://api.bts.blckchnd.com', no_broadcast=True)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/bitshares.py", line 144, in __init__
    **kwargs)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/bitshares.py", line 173, in connect
    self.rpc = BitSharesNodeRPC(node, rpcuser, rpcpassword, **kwargs)
  File "/home/vvk/.local/share/virtualenvs/DEXBot-XTl2tJdV/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitsharesapi/bitsharesnoderpc.py", line 24, in __init__
    self.chain_params = self.get_network()
AttributeError: can't set attribute
```

**Comment by bitfag** [comment]
Sorry, installing bitshares-0.1.18 solved the problem.
